openapi: 3.0.0
info:
  description: |
    Katze API is an API for cats.
    You can find out more about Swagger at
    [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  version: "1.0.0"
  title: Katze API
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/RamirezAlex/katze/1.0.0
  - url: 'https://catstore.swagger.io/v2'
tags:
  - name: katze
    description: Everything about cats
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
    externalDocs:
      description: Find out more about our store
      url: 'http://swagger.io'
paths:
  /cat:
    post:
      tags:
        - cat
      summary: Create a new cat
      operationId: createCat
      responses:
        '405':
          description: Invalid input
      security:
        - catstore_auth:
            - 'write:cats'
            - 'read:cats'
      requestBody:
        $ref: '#/components/requestBodies/cat'
  '/cat/{catId}':
    get:
      tags:
        - cat
      summary: Find cat by ID
      description: Returns a single cat
      operationId: getcatById
      parameters:
        - name: catId
          in: path
          description: ID of cat to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cat'
            application/xml:
              schema:
                $ref: '#/components/schemas/cat'
        '400':
          description: Invalid ID supplied
        '404':
          description: cat not found
      security:
        - api_key: []
    put:
      tags:
        - cat
      summary: Update an existing cat
      operationId: updatecat
      parameters:
        - name: catId
          in: path
          description: ID of cat that needs to be updated
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '405':
          description: Invalid input
      security:
        - catstore_auth:
            - 'write:cats'
            - 'read:cats'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  description: Updated name of the cat
                  type: string
                status:
                  description: Updated status of the cat
                  type: string
    delete:
      tags:
        - cat
      summary: Deletes a cat
      operationId: deletecat
      parameters:
        - name: api_key
          in: header
          required: false
          schema:
            type: string
        - name: catId
          in: path
          description: cat id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: cat not found
      security:
        - catstore_auth:
            - 'write:cats'
            - 'read:cats'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
components:
  schemas:
    cat:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: Milo
        name:
          type: string
          example: Black
        tags:
          type: array
          type: string
          example: ['cute', 'puppy', 'wild' ]
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  requestBodies:
    cat:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/cat'
        application/xml:
          schema:
            $ref: '#/components/schemas/cat'
      description: cat object that needs to be added to the store
      required: true
  securitySchemes:
    catstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://catstore.swagger.io/oauth/dialog'
          scopes:
            'write:cats': modify cats in your account
            'read:cats': read your cats
    api_key:
      type: apiKey
      name: api_key
      in: header
      